name: Code Checks

on:
  pull_request:
    paths:
      - '.github/workflows/ci-workflow.yml'
      - '**.kt'
      - '**.kts'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: run ktlint
        run: ./gradlew ktlintCheck
      - name: run unittest
        run: ./gradlew test
        continue-on-error: false