name: Code Style Check

on:
  pull_request:
    paths:
      - '.github/workflows/ktlint.yml'
      - 'src/**/*.kt'
      - '**.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install ktlint
        run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: run ktlint
        run: ktlint --reporter=checkstyle
        continue-on-error: false