name: Test Check

on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'src/**/*.kt'
      - '**.kts'

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: run unittest
        run: ./gradlew test
        continue-on-error: false